%Stability derivatives matrix initialization:

%Static
LD.cd=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));%
LD.cl=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));%
LD.cm=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));%
LD.cn=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));
LD.ca=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));
LD.xcp=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));
LD.cla=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));
LD.cma=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));
LD.cyb=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));%
LD.cnb=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));%
LD.clb=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build),length(LD.grndht),length(LD.delta));%
%Dynamic
LD.clq=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.cmq=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.clad=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.cmad=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.clp=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.cyp=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.cnp=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.cnr=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
LD.clr=zeros(length(LD.alpha),length(LD.mach),length(LD.alt),...
    length(LD.build));%
%High Lift (Not applicable but initialized)
LD.dcl_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));
LD.dcm_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));
LD.dclmax_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));
LD.dcdmin_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));
LD.clad_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));
LD.cha_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));
LD.chd_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));
LD.dcid_sym=zeros(length(LD.alpha),length(LD.mach),length(LD.alt));









