function [validData,Thrust,Power,Current,RPM,exitFlag] = loadMappedData(filename,...
    expectedMotorModel,expectedPropellerModel,expectedVoltageLim,expectedHeightLim,...
    expectedVflightLim,expectedVoltageLength,expectedHeightLength,expectedVflightLength) %#ok<STOUT>
%LOADMAPPEDDATA Summary of this function goes here
    
    %load data contained in file
    load(filename);
    
    if isequal(motorModel,     expectedMotorModel)     && ...
       isequal(propellerModel, expectedPropellerModel) && ...
       isequal(voltageLim,     expectedVoltageLim)     && ...
       isequal(heightLim,      expectedHeightLim)      && ...
       isequal(vflightLim,     expectedVflightLim)     && ...
       isequal(voltageLength,  expectedVoltageLength)  && ...
       isequal(heightLength,   expectedHeightLength)   && ...
       isequal(vflightLength,  expectedVflightLength)
        validData = 1;
    else
        validData = 0; 
    end

end

